<h2><i class="far fa-calendar-alt"></i> Évenements</h2>

<section class="events-create">
    <h3><i class="far fa-calendar-plus"></i> Ajouter un évenement</h3>
    <form action="evenements.php#navbar" method="POST">
        <input type="hidden" name="add">
        <div class="form-group">
            <label for="title">Titre:</label>
            <input type="text" class="form-control" name="title" required>
        </div>
        <div class="form-group">
            <label for="comment">Commentaire:</label>
            <textarea class="form-control" rows="5" name="comment"></textarea>
        </div> 
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">Date</span>
            </div>
            <input type="date" class="form-control" name="day" required>
            <select class="form-control" name="hour">
                <option value="matin">Matin</option>
                <option value="apres-midi">Après-midi</option>
                <option value="soir">Soir</option>
                <option value="jour">Journée entiére</option>
            </select> 
       </div>
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    </form>
</section>

<section>
    <h3><i class="far fa-calendar"></i> Modifier un évenement</h3>
    <table class="table table-striped">
    <thead>
        <tr class="table-light">
            <th>Titre</th>
            <th>Commentaire</th>
            <th>Date</th>
            <th>Heure</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($events as $evt){ ?>
            <tr class="table-light">
                <td><?= $evt["name"] ?></td>
                <td><?= $evt["comment"] ?></td>
                <td><?= $evt["date"] ?></td>
                <td><?= $evt["heure"] ?></td>
                <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modif<?= $evt['id'] ?>"><i class="far fa-comment"></i></button></td>
                <td><form action="evenements.php#navbar" method="POST">
                    <input type="text" name="delete" class="hidden" value="<?= $evt['id'] ?>">
                    <input type="text" name="res" class="hidden" value="<?= $evt['resId'] ?>">
                    <button type="submit" class="btn btn-danger"><i class="fas fa-times-circle"></i></button>
                </form></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
</section>

<?php foreach($events as $evt){ ?>
    <div class="modal fade" id="modif<?= $evt['id'] ?>">
        <div class="modal-dialog">
            <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Modifier l'évenement</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <form action="evenements.php#navbar" method="POST">
                <!-- Modal body -->
                <div class="modal-body">
                    <input type="hidden" name="modif">
                    <input type="hidden" name="id" value="<?= $evt['id'] ?>">
                    <div class="form-group">
                        <label for="title">Titre:</label>
                        <input type="text" class="form-control" name="title" value="<?= $evt['name'] ?>" required>
                    </div>
                    <div class="form-group">
                        <label for="comment">Commentaire:</label>
                        <textarea class="form-control" rows="5" name="comment"><?= $evt['comment'] ?></textarea>
                    </div> 
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Enregistrer</button>
                </div>
             </form>
            </div>
        </div>
    </div>
<?php } ?>
