<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Salle des fêtes du Plessis Robinson</title>

    <link rel="stylesheet" href="fontawesome/css/all.css">
    <link rel="stylesheet" href="bootstrap4/css/bootstrap.css">
    <link rel="stylesheet" href="slick/slick/slick.css">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>

        <!-- Image de presentation -->
        <div class="acceuil text-center ">
<h1 class="acceuil-title card bg-secondary text-white"><a href="#navbar" class="card-body">La salle des fêtes du Plessis Robinson vous souhaite la bienvenue<?php if(array_key_exists("userName", $_SESSION)){ ?>, <?= $_SESSION["userName"] ?> <?php } ?></a></h1>
        </div>
     </header>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark header-nav sticky-top" id="navbar">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon" id="buttonNav"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item link-index">
                    <a class="nav-link" href="index.php#navbar"><i class="fas fa-home"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contact.php#navbar">Nous contacter</a>
                </li>
                <li class="nav-item">
                    <a href="livre_d_or.php#navbar" class="nav-link">Livre d'or</a>
                </li>
                <li class="nav-item">
                    <div class="nav-link dropdown">
                        <a href="reservation.php#navbar">Reserver</a>
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown"></a>
                        <div class="dropdown-menu nav-drop">
                            <a class="dropdown-item secondary-link" href="reserver.php#navbar">Formulaire de réservation</a>
                        </div>
                    </div>
                </li>
                <?php if (!array_key_exists("role", $_SESSION)) { ?>
                    <li class="nav-item">
                        <a class="nav-link" href="register.php#navbar">S'inscrire</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#connexion">Se connecter</a>
                    </li>
                <?php }elseif($_SESSION["role"] === "guest") { ?>
                    <li class="link-item dropdown">
                        <a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown"><i class="fas fa-user-circle"></i> Compte</a>
                        <div class="dropdown-menu nav-drop">
                            <a class="dropdown-item secondary-link" href="compte.php#navbar">Mon compte</a>
                            <a class="dropdown-item" href="mes_reservations.php#navbar">Mon historique</a>
                            <a class="dropdown-item" href="logout.php"><i class="fas fa-door-closed"></i> Se déconnecter</a>
                        </div>
                    </li>
                <?php }else{ ?>
                    <!-- TODO: modifier link vers adm -->
                    <li class="nav-item">
                        <?php $mail = getMail() ?>
                        <a href="messages.php#navbar" class="nav-link"><i class="fas fa-envelope"></i> <?php if($mail > 0){ ?><span class="badge badge-danger"><?= $mail ?></span> Msg non lus<?php } ?></a>
                    </li>
                    <li class="link-item dropdown">
                        <a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown"><i class="fas fa-user-cog"></i> Administration</a>
                        <div class="dropdown-menu nav-drop">
                            <a class="dropdown-item secondary-link" href="compte.php#navbar">Mon compte</a>
                            <!-- TODO: faire slider -->
                            <!-- <a class="dropdown-item" href="slider.php#navbar">Slider</a> -->
                            <a class="dropdown-item" href="historique.php#navbar">Historique des réservations</a>
                            <a class="dropdown-item" href="evenements.php#navbar">Gérer les évenements</a>
                            <a class="dropdown-item" href="logout.php">Se déconnecter <i class="fas fa-door-closed"></i></a>
                        </div>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </nav>

    <section class="modal fade" id="connexion">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content text-center">

                <?php if(!empty($_GET)){ ?>
                    <?php if($_GET["error"] === "id"){ ?>
                        <div id="loginError" class="alert alert-danger alert-dismissible fade show">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <p>Identifiant ou adresse mail invalide</p>
                        </div>
                    <?php }elseif($_GET["error"] === "mdp"){ ?>
                        <div id="loginError" class="alert alert-danger alert-dismissible fade show">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <p>Mauvais mot de passe</p>
                        </div>
                    <?php } ?>
                <?php } ?>
                <!-- Modal Header -->
                <div class="modal-header text-center ">
                    <h4 class="modal-title w-100">Connexion</h4>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <!-- TODO: remember me -->
                    <form action="login.php" method="post">
                        <fieldset class="form-group">
                            <label for="identifiant">Votre Pseudonyme ou adresse mail:</label>
                            <input type="text" class="form-control" id="identifiant" placeholder="Identifiant" name="identifiant">
                        </fieldset>
                        <fieldset class="form-group">
                            <label for="mdp">Votre mot de passe:</label>
                            <input type="password" class="form-control" id="mdp" placeholder="Mot de passe" name="mdp">
                        </fieldset>
                        <button type="submit" class="btn btn-primary">Se connecter</button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Annuler</button>
                    </form>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <small>Pour se connecter en tant qu'administrateur, utiliser Admin en identifiant et admin en mot de passe</small>
                    <small>Pour se connecter en tant que client, utiliser Client en identifiant et client en mot de passe</small>
                    <small>Vous pouvez aussi créer vos propre identifiants et mot de passe en vous inscrivant en tant que client</small>
                </div>

            </div>
        </div>

    </section>

    
    <main class="container">

    <?php  include $template.'.phtml'; ?>

    </main>

    <!-- Juste au cas où -->
    <footer>

        <!-- TODO: Arranger le disclaimer -->
        <div class="card bg-secondary text-white">
            <small class="container-fluid text-center card-body">Ce site internet est un projet personnel visant à démontrer mes capacités de développement d'un site internet. Je ne suis ni propriétaire du batiment, ni de la salle. Toute réservation faite sur ce site existe dans le but de tester le fonctionnement du code.</small>
        </div>

        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <ul class="navbar-nav">
                <li class="navbar-item">
                    <a href="mailto:thierrylependuu@gmail.com" class="navbar-link">M'envoyer un email</a>
                </li>
                <li class="navbar-item">
                    <a href="http://www.linkedin.com/in/thierry-lependu" target="blank" class="navbar-link">Mon Linkedin</a>
                </li>
                <li class="navbar-item">
                    <!-- TODO: ajouter adresse portfolio -->
                    <a href="www.portfoliolependuthierry.fr" target="blank" class="navbar-link">Mon portfolio</a>
                </li>
                <li class="navbar-item">
                    <a href="https://github.com/thierrylependu" target="blank" class="navbar-link">Mon GitHub</a>
                </li>
            </ul>
        </nav>

    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="bootstrap4/js/bootstrap.js"></script>
    <script src="slick/slick/slick.js"></script>
    <script src="js/main.js"></script>
</body>
<!-- <script type="text/javascript" src="js/main.js"></script> -->
</html>