<section class="rules rounded-lg">
    <h2>Comment réserver ?</h2>
    <p>La salle des fêtes du Plessis Robinson peut être réservée en remplissant le formulaire <a href="#lienFormulaire">en bas de la page</a>. La possession d'un compte sur le site permet de faciliter la réservation, ainsi que de garder un historique des réservations éffectuées.Les réservations peuvent être faite pour une matinée, une après-midi, une soirée ou pour la journée compléte. Une réservation coute 70€, à régler en envoyant un chéque <a href="contact.php#navbar" target="_blank">à cette adresse</a> ou en payant par PayPal. La réservation d'une salle ne sera confirmée qu'après confirmation du paiement. Les clients sont tenus de réspecter les régles ci-dessous pour la réservation de la salle.</p>
</section>

<br>

<section class="rules rounded-lg">
    <h2>Les règles</h2>
    <p>Les clients ayants réservé sont priés de réspecter les règles suivantes :</p>
    <ul>
        <li>Toute perte, destruction ou dégradation de matériel devra être remboursée par le client</li>
        <li>A la fin du créneau réservé, le client devra ranger et nettoyer la salle</li>
        <li>Aucun tapage nocturne ne sera toléré.</li>
    </ul>
    <p>Si vous accepter ces règles, vous pouvez remplir le formulaire <a href="#lienFormulaire">en bas de la page</a>.</p>
</section>

<br>

<section class="rules rounded-lg">
    <h2>Les crénaux</h2>
    <p>Les réservations se font par créneaux, avec un prix de 70€ chacun. Une matinée va de 7 heure à 12 heure, une après-midi va de 13 heure à 18 heure et une soirée va de 19 heure à 24 heure. Le client aura une demi-heure de plus au début et à la fin du créneau pour l'installation et le rangement de la salle.</p>
</section>

<br>

<section class="rules rounded-lg">
    <h2>Si vous avez des questions</h2>
    <p>Si vous avez des questions, vous pouvez nous contacter sur <a href="contact.php#navbar">cette page</a>. Vous pourrez nous envoyez un email, nous contacter par télèphone ou nous laisser un message sur le site.</p>
</section>


<a href="reserver.php#navbar" class="btn btn-primary" id="lienFormulaire">Accéder au formulaire de réservation</a>